// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxhnszhvdzbtmlqqewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeGhuc3podmR6YnRtbHFxZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA5MDIsImV4cCI6MjA2NTU0NjkwMn0.6fI726Sjk350H8mbkGvKKGSvdHgLpyoPzUatBHoDSLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);